# Generated by Django 3.2.13 on 2022-06-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_advertising',
            field=models.BooleanField(default=False, verbose_name='Is advertising'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_animations',
            field=models.BooleanField(default=False, verbose_name='Is animations'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_architecture',
            field=models.BooleanField(default=False, verbose_name='Is architecture'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_archives',
            field=models.BooleanField(default=False, verbose_name='Is archives'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_artscrafts',
            field=models.BooleanField(default=False, verbose_name='Is Arts crafts'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_book',
            field=models.BooleanField(default=False, verbose_name='Is book'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_celebrations',
            field=models.BooleanField(default=False, verbose_name='Is celebrations'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_comics',
            field=models.BooleanField(default=False, verbose_name='Is comics'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_creativeeventservices',
            field=models.BooleanField(default=False, verbose_name='Is creative event services'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_creativerd',
            field=models.BooleanField(default=False, verbose_name='Is creative R&D'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_dance',
            field=models.BooleanField(default=False, verbose_name='Is dance'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_digital',
            field=models.BooleanField(default=False, verbose_name='Is digital'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_digitalcontent',
            field=models.BooleanField(default=False, verbose_name='Is digital content'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_digitalservices',
            field=models.BooleanField(default=False, verbose_name='Is creative digital services'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_fashion',
            field=models.BooleanField(default=False, verbose_name='Is fashion'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_fastival',
            field=models.BooleanField(default=False, verbose_name='Is fastival'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_film',
            field=models.BooleanField(default=False, verbose_name='Is film'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_graphics',
            field=models.BooleanField(default=False, verbose_name='Is graphics'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_historical',
            field=models.BooleanField(default=False, verbose_name='Is historical'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_interiordesign',
            field=models.BooleanField(default=False, verbose_name='Is interior design'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_jewellery',
            field=models.BooleanField(default=False, verbose_name='Is jewellery'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_libraries',
            field=models.BooleanField(default=False, verbose_name='Is libraries'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_livemusic',
            field=models.BooleanField(default=False, verbose_name='Is live music'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_magazines',
            field=models.BooleanField(default=False, verbose_name='Is magazines'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_museums',
            field=models.BooleanField(default=False, verbose_name='Is museums'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_musicvideo',
            field=models.BooleanField(default=False, verbose_name='Is music video '),
        ),
        migrations.AddField(
            model_name='user',
            name='is_opera',
            field=models.BooleanField(default=False, verbose_name='Is opera'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_painting',
            field=models.BooleanField(default=False, verbose_name='Is painting'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_photography',
            field=models.BooleanField(default=False, verbose_name='Is photography'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_pottery',
            field=models.BooleanField(default=False, verbose_name='Is pottery'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_puppetry',
            field=models.BooleanField(default=False, verbose_name='Is puppetry'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_radio',
            field=models.BooleanField(default=False, verbose_name='Is radio'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_sculpture',
            field=models.BooleanField(default=False, verbose_name='Is sculpture'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_software',
            field=models.BooleanField(default=False, verbose_name='Is software'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_television',
            field=models.BooleanField(default=False, verbose_name='Is television'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_theater',
            field=models.BooleanField(default=False, verbose_name='Is theater'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_toys',
            field=models.BooleanField(default=False, verbose_name='Is toys'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_videogames',
            field=models.BooleanField(default=False, verbose_name='Is video games'),
        ),
    ]
