# Generated by Django 3.2.13 on 2022-06-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='landind_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binner', models.FileField(null=True, upload_to='videos/%Y/%m/%d/')),
            ],
        ),
    ]
