# Generated by Django 3.2.13 on 2022-06-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0002_alter_landind_page_binner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landind_page',
            name='binner',
            field=models.FileField(upload_to='videos/%Y/%m/%d/'),
        ),
    ]
