# Generated by Django 3.2.13 on 2022-06-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0003_alter_landind_page_binner'),
    ]

    operations = [
        migrations.AddField(
            model_name='landind_page',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
