# Generated by Django 3.2.13 on 2022-06-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0004_landind_page_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logo/%Y/%m/%d/')),
            ],
        ),
        migrations.RemoveField(
            model_name='landind_page',
            name='title',
        ),
    ]
