# Generated by Django 3.2.13 on 2022-06-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0005_auto_20220609_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='operate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operate', models.TextField(max_length=200)),
            ],
        ),
    ]
