# Generated by Django 3.2.13 on 2022-06-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0006_operate'),
    ]

    operations = [
        migrations.CreateModel(
            name='copyright',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copy', models.IntegerField()),
            ],
        ),
    ]
