# Generated by Django 3.2.13 on 2022-06-09 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0007_copyright'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='copyright',
            new_name='copy_right',
        ),
    ]
