# Generated by Django 3.2.13 on 2022-06-10 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0008_rename_copyright_copy_right'),
    ]

    operations = [
        migrations.CreateModel(
            name='quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('year', models.IntegerField(blank=True)),
                ('quote', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
