# Generated by Django 3.2.13 on 2022-06-10 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0010_alter_quote_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='author',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
