# Generated by Django 3.2.13 on 2022-06-10 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0011_auto_20220610_1100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='quote',
            new_name='quotes',
        ),
    ]
