# Generated by Django 3.2.13 on 2022-06-10 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0012_rename_quote_quote_quotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traditional_cultural_expression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_no', models.CharField(max_length=100)),
            ],
        ),
    ]
