# Generated by Django 3.2.13 on 2022-06-10 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0013_traditional_cultural_expression'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Traditional_cultural_expression',
        ),
    ]
