# Generated by Django 4.0.4 on 2022-05-10 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='authUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.IntegerField(default=1)),
                ('phone_no', models.IntegerField(unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date_joined')),
                ('country', models.CharField(choices=[('select', '---select Countries---'), ('Bhutan', 'Bhutan'), ('India', 'India'), ('USA', 'USA')], default='select', max_length=32)),
                ('Dzongkhag', models.CharField(choices=[('select', '---select Dzongkhag---'), ('Bumthang', 'Bumthang'), ('Chukha', 'Chukha'), ('Dagana', 'Dagana'), ('Gasa', 'Gasa'), ('Haa', 'Haa'), ('Lhuntse', 'Lhuntse'), ('Mongar', 'Mongar'), ('Paro', 'Paro'), ('Pemagatshel', 'Pemagatshel'), ('Punakha', 'Punakha'), ('Samdrup Jongkhar ', 'Samdrup Jongkhar '), ('Samtse', 'Samtse'), ('Sarpang', 'Sarpang'), ('Thimphu', 'Thimphu'), ('Trashigang', 'Trashigang'), ('Trashiyangtse', 'Trashiyangtse'), ('Trongsa', 'Trongsa'), ('Tsirang', 'Tsirang'), ('Wangdue Phodrang', 'Wangdue Phodrang'), ('Zhemgang', 'Zhemgang')], default='select', max_length=32)),
                ('marital_status', models.CharField(choices=[('select', '---select maritals---'), ('Single', 'Single'), ('Married', 'Married')], default='select', max_length=32)),
                ('employment_status', models.CharField(choices=[('select', '---select employment---'), ('Employed', 'Employed'), ('Unemployed', 'Unemployed'), ('Student', 'Student'), ('Business', 'Business')], default='select', max_length=32)),
                ('skills', models.CharField(blank=True, choices=[('select', '---select skills---'), ('artist', 'artist')], default='select', max_length=32)),
                ('document', models.FileField(null=True, upload_to='documents/')),
                ('remarks', models.TextField(blank=True, max_length=300)),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='artist_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=100, unique=True)),
                ('is_show_mail', models.BooleanField(default=True, verbose_name='show')),
                ('phone', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('is_show', models.BooleanField(default=True, verbose_name='show')),
                ('name', models.CharField(max_length=100)),
                ('pubprofile', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('pubcountry', models.CharField(choices=[('select', '---select Countries---'), ('Bhutan', 'Bhutan'), ('India', 'India'), ('USA', 'USA')], default='select', max_length=32)),
                ('pudDzongkhag', models.CharField(choices=[('select', '---select Dzongkhag---'), ('Bumthang', 'Bumthang'), ('Chukha', 'Chukha'), ('Dagana', 'Dagana'), ('Gasa', 'Gasa'), ('Haa', 'Haa'), ('Lhuntse', 'Lhuntse'), ('Mongar', 'Mongar'), ('Paro', 'Paro'), ('Pemagatshel', 'Pemagatshel'), ('Punakha', 'Punakha'), ('Samdrup Jongkhar ', 'Samdrup Jongkhar '), ('Samtse', 'Samtse'), ('Sarpang', 'Sarpang'), ('Thimphu', 'Thimphu'), ('Trashigang', 'Trashigang'), ('Trashiyangtse', 'Trashiyangtse'), ('Trongsa', 'Trongsa'), ('Tsirang', 'Tsirang'), ('Wangdue Phodrang', 'Wangdue Phodrang'), ('Zhemgang', 'Zhemgang')], default='select', max_length=32)),
                ('pubmarital_status', models.CharField(choices=[('select', '---select maritals---'), ('Single', 'Single'), ('Married', 'Married')], default='select', max_length=32)),
                ('pubemployment_status', models.CharField(choices=[('select', '---select employment---'), ('Employed', 'Employed'), ('Unemployed', 'Unemployed'), ('Student', 'Student'), ('Business', 'Business')], default='select', max_length=32)),
                ('pubskills', models.CharField(blank=True, choices=[('select', '---select skills---'), ('Artist', 'Artist')], default='select', max_length=32)),
                ('pubdocument', models.FileField(null=True, upload_to='documents/')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date_joined')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
