# Generated by Django 4.0.5 on 2022-06-19 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authuser',
            old_name='phone_no',
            new_name='cell_number',
        ),
    ]
