# Generated by Django 4.0.4 on 2022-05-10 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addevent',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='show'),
        ),
    ]
