# Generated by Django 3.2.13 on 2022-06-07 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_addevent_is_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addevent',
            old_name='image',
            new_name='image_event',
        ),
    ]
