# Generated by Django 3.2.13 on 2022-06-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_rename_image_addevent_image_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addevent',
            name='image_event',
            field=models.ImageField(upload_to='event/'),
        ),
    ]
