# Generated by Django 4.0.4 on 2022-05-05 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='creation_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discription', models.TextField(max_length=200)),
                ('creation_title', models.CharField(max_length=100)),
                ('creation_type', models.CharField(choices=[('select', '---select Design ---'), ('Fashion', 'Fashion'), ('Jewellery', 'Jewellery'), ('Toys', 'Toys'), ('Interior/Set Design', 'Interior/Set Design'), ('Graphics', 'Graphics')], default='select', max_length=32)),
                ('image', models.ImageField(blank=True, null=True, upload_to='heriage/')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='auth_creation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.IntegerField(default=1)),
                ('phone_no', models.IntegerField(unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date_joined')),
                ('skills', models.CharField(blank=True, choices=[('select', '---select skills---'), ('Artist', 'Artist')], default='select', max_length=32)),
                ('document', models.FileField(null=True, upload_to='documents/')),
                ('remarks', models.TextField(blank=True, max_length=300)),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
