# Generated by Django 4.0.4 on 2022-05-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authart',
            name='skills',
            field=models.CharField(choices=[('select', '---select skills---'), ('Artist', 'Artist')], default='select', max_length=32),
        ),
    ]
